version: '3'

services:
  app:
    build:
      context: .
    links:
      - db
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vk-app
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vk-app