version: '3.8'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    env_file:
      - .env    
  db:
    image: postgres:15.2-alpine
    env_file:
      - .env
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
